### ISSUE TITLE
由于Content-Security-Policy在chrome console中无法执行

### ISSUE THREAD

**Issue by 0x11-dev** [wintercn/dog-fucked-zhihu#2]
`
Content-Security-Policy: default-src *; frame-src *.zhihu.com getpocket.com note.youdao.com; script-src *.zhihu.com *.google-analytics.com zhstatic.zhihu.com 'unsafe-eval'; style-src *.zhihu.com 'unsafe-inline'
`

**Comment by hudidit** [comment]
@levin-du  在 http://www.zhihu.com/people/{username} 页面的 console 里可以用啊

**Comment by wintercn** [comment]
不要用iframe，在自己的个人页面用
