### ISSUE TITLE
http://www.zhihu.com/draft/get页面打不开

### ISSUE THREAD

**Issue by YaoZeyuan** [wintercn/dog-fucked-zhihu#7]
http://www.zhihu.com/draft/get?qid=4296931一点就是500错误，是知乎服务器换API了吗？
以及，r应该是result的意思，在登陆窗口如果结果不正确的话r就会有值，比如密码错误和需要输入验证码返回的r值就不一样

**Comment by wintercn** [comment]
qid是我的答案，你点当然打不开。

**Comment by wintercn** [comment]
qid=4296931是我的答案，你点当然打不开。
